import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useContext, useEffect, useState } from "react";

export type LangCode = "fr" | "en" | "es" | "zh" | "ru";

export const LANGS: { code: LangCode; label: string; flag: string }[] = [
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "zh", label: "中文", flag: "🇨🇳" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
];

const LANG_KEY = "@gitcrush_lang";

type Dict = Record<string, string>;

const fr: Dict = {
  // Login
  "login.tagline": "Connectez-vous avec votre compte GitHub",
  "login.howTo": "Comment se connecter",
  "login.step1": "Cliquez sur « Créer un token » ci-dessous",
  "login.step2": "Activez le scope « repo » puis générez le token",
  "login.step3": "Copiez le token et collez-le dans le champ ci-dessous",
  "login.tokenLabel": "Personal Access Token",
  "login.tokenRequired": "Veuillez entrer votre token GitHub",
  "login.tokenInvalid": "Token invalide. Vérifiez vos droits (scope: repo)",
  "login.connect": "Se connecter",
  "login.createToken": "Créer un token GitHub",
  "login.note": "Votre token est stocké localement et n'est jamais partagé.",
  "login.chooseLang": "Choisir la langue",
  // Tabs
  "tabs.home": "Accueil",
  "tabs.files": "Fichiers",
  "tabs.profile": "Profil",
  // Home
  "home.add": "AJOUTER",
  "home.noCommits": "AUCUN COMMIT TROUVÉ...",
  "home.selectRepoHint": "Sélectionnez un dépôt pour voir les commits",
  "home.currentBranch": "BRANCHE ACTUELLE",
  "home.unborn": "AUCUNE BRANCHE",
  "home.syncChanges": "SYNC LES MODIFICATIONS",
  "home.synced": "Commits actualisés",
  "home.remoteOrigin": "DISTANT · ORIGIN",
  "home.none": "Aucun...",
  "home.clone": "CLONER",
  "home.auth": "AUTH",
  "home.directory": "RÉPERTOIRE",
  "home.noRepoSelected": "Aucun dépôt sélectionné...",
  "home.gitFilters": "GIT FILTERS",
  "home.gitFiltersHint": "Les commits des 30 derniers jours de la branche active sont affichés.",
  "home.appSync": "Paramètres de synchronisation",
  "home.appSyncHint": "Configurez vos préférences de synchronisation dans l'onglet Fichiers.",
  "home.scheduledSync": "PARAMÈTRES DE SYNC PLANIFIÉE",
  "home.scheduledSyncHint": "La synchronisation planifiée arrive bientôt.",
  "home.chooseBranch": "Changer de branche",
  "home.chooseRepo": "Choisir un dépôt",
  "home.notifsOn": "Notifications activées",
  "home.notifsOff": "Notifications désactivées",
  "home.selectRepoFirst": "Sélectionnez un dépôt d'abord",
  // Files
  "files.title": "Fichiers",
  "files.clearSelection": "Vider",
  "files.repo": "DÉPÔT",
  "files.selectRepo": "Sélectionner un dépôt...",
  "files.search": "Rechercher...",
  "files.noRepoFound": "Aucun dépôt trouvé",
  "files.branch": "BRANCHE",
  "files.targetPath": "CHEMIN CIBLE (optionnel)",
  "files.targetPathPh": "ex: src/components",
  "files.commitMsg": "MESSAGE DE COMMIT",
  "files.commitMsgPh": "Message de commit...",
  "files.file": "FICHIER",
  "files.pickFile": "Sélectionner un fichier",
  "files.replaceFile": "Remplacer le fichier",
  "files.zipHint": "Un .zip est automatiquement extrait. Le sous-dossier racine commun (ex: « projet-main/ ») est détecté et retiré pour pusher à la racine. Les archives .rar ne sont pas supportées : convertissez-les en .zip.",
  "files.pushZip": "Extraire et pusher le zip",
  "files.pushFile": "Pusher le fichier",
  "files.deleteDir": "SUPPRIMER UN RÉPERTOIRE",
  "files.deleteDirPh": "ex: src/old-components",
  "files.deleteDirBtn": "Supprimer le répertoire",
  "files.clearRepo": "VIDER LE DÉPÔT",
  "files.clearRepoHint": "Supprime TOUS les fichiers du dépôt en un seul commit. Action irréversible.",
  "files.clearRepoBtn": "Vider le dépôt",
  // Messages
  "msg.error": "Erreur",
  "msg.success": "Succès",
  "msg.cancel": "Annuler",
  "msg.ok": "OK",
  "msg.viewCommits": "Voir les commits",
  "msg.unknownError": "Erreur inconnue",
  "msg.selectRepoFirst": "Sélectionnez un dépôt d'abord",
  "msg.noFileSelected": "Aucun fichier sélectionné",
  "msg.enterCommitMsg": "Entrez un message de commit",
  "msg.pickFail": "Impossible de sélectionner le fichier",
  "msg.zipEmpty": "Le zip est vide ou illisible",
  "msg.rarUnsupported": "Les archives .rar ne peuvent pas être extraites sur mobile. Convertissez l'archive en .zip puis réessayez : la détection du sous-dossier racine fonctionnera automatiquement.",
  "msg.filesPushed": "{done}/{total} fichier(s) pushé(s) vers {repo}/{branch}",
  "msg.subfolderStripped": "(Sous-dossier « {prefix} » détecté et retiré)",
  "msg.filePushed": "Fichier pushé vers {repo}/{branch} (stratégie {strategy})",
  "msg.errors": "Erreurs",
  "msg.andOthers": "… et {n} autre(s)",
  "msg.enterDeletePath": "Entrez le chemin du répertoire à supprimer",
  "msg.confirmDeleteTitle": "Confirmer la suppression",
  "msg.confirmDeleteBody": "Supprimer définitivement « {path} » (et tout son contenu) de {repo}/{branch} ?",
  "msg.deleteAction": "Supprimer",
  "msg.dirDeleted": "Répertoire supprimé ({n} fichier(s) retiré(s)).",
  "msg.confirmClearTitle": "⚠️ Vider le dépôt",
  "msg.confirmClearBody": "Cette action supprimera TOUS les fichiers de {repo}/{branch}. Cette opération est irréversible.\n\nContinuer ?",
  "msg.clearAction": "Vider le dépôt",
  "msg.repoCleared": "Dépôt vidé — {n} fichier(s) supprimé(s).",
  // Settings
  "settings.title": "Paramètres",
  "settings.account": "COMPTE",
  "settings.githubProfile": "Profil GitHub",
  "settings.repos": "Dépôts",
  "settings.reposBadge": "dépôts",
  "settings.app": "APPLICATION",
  "settings.version": "Version",
  "settings.language": "Langue",
  "settings.danger": "DANGER",
  "settings.logout": "Se déconnecter",
  "settings.logoutConfirmTitle": "Se déconnecter",
  "settings.logoutConfirmBody": "Votre token sera supprimé de l'appareil. Continuer ?",
  "settings.logoutAction": "Déconnecter",
};

const en: Dict = {
  "login.tagline": "Sign in with your GitHub account",
  "login.howTo": "How to sign in",
  "login.step1": "Tap « Create a token » below",
  "login.step2": "Enable the « repo » scope, then generate the token",
  "login.step3": "Copy the token and paste it in the field below",
  "login.tokenLabel": "Personal Access Token",
  "login.tokenRequired": "Please enter your GitHub token",
  "login.tokenInvalid": "Invalid token. Check your permissions (scope: repo)",
  "login.connect": "Sign in",
  "login.createToken": "Create a GitHub token",
  "login.note": "Your token is stored locally and never shared.",
  "login.chooseLang": "Choose language",
  "tabs.home": "Home",
  "tabs.files": "Files",
  "tabs.profile": "Profile",
  "home.add": "ADD",
  "home.noCommits": "NO COMMITS FOUND...",
  "home.selectRepoHint": "Select a repository to see commits",
  "home.currentBranch": "CURRENT BRANCH",
  "home.unborn": "UNBORN BRANCH",
  "home.syncChanges": "SYNC CHANGES",
  "home.synced": "Commits refreshed",
  "home.remoteOrigin": "REMOTE · ORIGIN",
  "home.none": "None...",
  "home.clone": "CLONE",
  "home.auth": "AUTH",
  "home.directory": "DIRECTORY",
  "home.noRepoSelected": "No repository selected...",
  "home.gitFilters": "GIT FILTERS",
  "home.gitFiltersHint": "Showing the latest commits of the active branch.",
  "home.appSync": "App Sync Settings",
  "home.appSyncHint": "Configure your sync preferences in the Files tab.",
  "home.scheduledSync": "SCHEDULED SYNC SETTINGS",
  "home.scheduledSyncHint": "Scheduled sync is coming soon.",
  "home.chooseBranch": "Switch branch",
  "home.chooseRepo": "Choose a repository",
  "home.notifsOn": "Notifications enabled",
  "home.notifsOff": "Notifications disabled",
  "home.selectRepoFirst": "Select a repository first",
  "files.title": "Files",
  "files.clearSelection": "Clear",
  "files.repo": "REPOSITORY",
  "files.selectRepo": "Select a repository...",
  "files.search": "Search...",
  "files.noRepoFound": "No repository found",
  "files.branch": "BRANCH",
  "files.targetPath": "TARGET PATH (optional)",
  "files.targetPathPh": "e.g. src/components",
  "files.commitMsg": "COMMIT MESSAGE",
  "files.commitMsgPh": "Commit message...",
  "files.file": "FILE",
  "files.pickFile": "Pick a file",
  "files.replaceFile": "Replace file",
  "files.zipHint": "A .zip is extracted automatically. The common root subfolder (e.g. “project-main/”) is detected and stripped so files land at the root. .rar archives are not supported: convert them to .zip.",
  "files.pushZip": "Extract & push zip",
  "files.pushFile": "Push file",
  "files.deleteDir": "DELETE A DIRECTORY",
  "files.deleteDirPh": "e.g. src/old-components",
  "files.deleteDirBtn": "Delete directory",
  "files.clearRepo": "EMPTY THE REPOSITORY",
  "files.clearRepoHint": "Deletes ALL files of the repository in a single commit. Irreversible.",
  "files.clearRepoBtn": "Empty repository",
  "msg.error": "Error",
  "msg.success": "Success",
  "msg.cancel": "Cancel",
  "msg.ok": "OK",
  "msg.viewCommits": "View commits",
  "msg.unknownError": "Unknown error",
  "msg.selectRepoFirst": "Select a repository first",
  "msg.noFileSelected": "No file selected",
  "msg.enterCommitMsg": "Enter a commit message",
  "msg.pickFail": "Could not pick the file",
  "msg.zipEmpty": "The zip is empty or unreadable",
  "msg.rarUnsupported": ".rar archives cannot be extracted on mobile. Convert the archive to .zip and try again: root-subfolder detection will work automatically.",
  "msg.filesPushed": "{done}/{total} file(s) pushed to {repo}/{branch}",
  "msg.subfolderStripped": "(Subfolder “{prefix}” detected and stripped)",
  "msg.filePushed": "File pushed to {repo}/{branch} (strategy {strategy})",
  "msg.errors": "Errors",
  "msg.andOthers": "… and {n} more",
  "msg.enterDeletePath": "Enter the directory path to delete",
  "msg.confirmDeleteTitle": "Confirm deletion",
  "msg.confirmDeleteBody": "Permanently delete “{path}” (and all its contents) from {repo}/{branch}?",
  "msg.deleteAction": "Delete",
  "msg.dirDeleted": "Directory deleted ({n} file(s) removed).",
  "msg.confirmClearTitle": "⚠️ Empty repository",
  "msg.confirmClearBody": "This will delete ALL files of {repo}/{branch}. This operation is irreversible.\n\nContinue?",
  "msg.clearAction": "Empty repository",
  "msg.repoCleared": "Repository emptied — {n} file(s) deleted.",
  "settings.title": "Settings",
  "settings.account": "ACCOUNT",
  "settings.githubProfile": "GitHub profile",
  "settings.repos": "Repositories",
  "settings.reposBadge": "repos",
  "settings.app": "APPLICATION",
  "settings.version": "Version",
  "settings.language": "Language",
  "settings.danger": "DANGER",
  "settings.logout": "Sign out",
  "settings.logoutConfirmTitle": "Sign out",
  "settings.logoutConfirmBody": "Your token will be removed from this device. Continue?",
  "settings.logoutAction": "Sign out",
};

const es: Dict = {
  "login.tagline": "Inicia sesión con tu cuenta de GitHub",
  "login.howTo": "Cómo iniciar sesión",
  "login.step1": "Pulsa « Crear un token » abajo",
  "login.step2": "Activa el scope « repo » y genera el token",
  "login.step3": "Copia el token y pégalo en el campo de abajo",
  "login.tokenLabel": "Personal Access Token",
  "login.tokenRequired": "Introduce tu token de GitHub",
  "login.tokenInvalid": "Token no válido. Revisa tus permisos (scope: repo)",
  "login.connect": "Iniciar sesión",
  "login.createToken": "Crear un token de GitHub",
  "login.note": "Tu token se guarda localmente y nunca se comparte.",
  "login.chooseLang": "Elegir idioma",
  "tabs.home": "Inicio",
  "tabs.files": "Archivos",
  "tabs.profile": "Perfil",
  "home.add": "AÑADIR",
  "home.noCommits": "NO SE ENCONTRARON COMMITS...",
  "home.selectRepoHint": "Selecciona un repositorio para ver los commits",
  "home.currentBranch": "RAMA ACTUAL",
  "home.unborn": "SIN RAMA",
  "home.syncChanges": "SINCRONIZAR CAMBIOS",
  "home.synced": "Commits actualizados",
  "home.remoteOrigin": "REMOTO · ORIGIN",
  "home.none": "Ninguno...",
  "home.clone": "CLONAR",
  "home.auth": "AUTH",
  "home.directory": "DIRECTORIO",
  "home.noRepoSelected": "Ningún repositorio seleccionado...",
  "home.gitFilters": "FILTROS GIT",
  "home.gitFiltersHint": "Se muestran los últimos commits de la rama activa.",
  "home.appSync": "Ajustes de sincronización",
  "home.appSyncHint": "Configura tus preferencias en la pestaña Archivos.",
  "home.scheduledSync": "SINCRONIZACIÓN PROGRAMADA",
  "home.scheduledSyncHint": "La sincronización programada llegará pronto.",
  "home.chooseBranch": "Cambiar de rama",
  "home.chooseRepo": "Elegir un repositorio",
  "home.notifsOn": "Notificaciones activadas",
  "home.notifsOff": "Notificaciones desactivadas",
  "home.selectRepoFirst": "Selecciona primero un repositorio",
  "files.title": "Archivos",
  "files.clearSelection": "Quitar",
  "files.repo": "REPOSITORIO",
  "files.selectRepo": "Seleccionar un repositorio...",
  "files.search": "Buscar...",
  "files.noRepoFound": "Ningún repositorio encontrado",
  "files.branch": "RAMA",
  "files.targetPath": "RUTA DESTINO (opcional)",
  "files.targetPathPh": "ej: src/components",
  "files.commitMsg": "MENSAJE DE COMMIT",
  "files.commitMsgPh": "Mensaje de commit...",
  "files.file": "ARCHIVO",
  "files.pickFile": "Seleccionar un archivo",
  "files.replaceFile": "Reemplazar archivo",
  "files.zipHint": "Un .zip se extrae automáticamente. El subdirectorio raíz común (ej: «proyecto-main/») se detecta y se elimina para subir a la raíz. Los .rar no están soportados: conviértelos a .zip.",
  "files.pushZip": "Extraer y subir el zip",
  "files.pushFile": "Subir el archivo",
  "files.deleteDir": "ELIMINAR UN DIRECTORIO",
  "files.deleteDirPh": "ej: src/old-components",
  "files.deleteDirBtn": "Eliminar directorio",
  "files.clearRepo": "VACIAR EL REPOSITORIO",
  "files.clearRepoHint": "Elimina TODOS los archivos del repositorio en un solo commit. Irreversible.",
  "files.clearRepoBtn": "Vaciar repositorio",
  "msg.error": "Error",
  "msg.success": "Éxito",
  "msg.cancel": "Cancelar",
  "msg.ok": "OK",
  "msg.viewCommits": "Ver commits",
  "msg.unknownError": "Error desconocido",
  "msg.selectRepoFirst": "Selecciona primero un repositorio",
  "msg.noFileSelected": "Ningún archivo seleccionado",
  "msg.enterCommitMsg": "Introduce un mensaje de commit",
  "msg.pickFail": "No se pudo seleccionar el archivo",
  "msg.zipEmpty": "El zip está vacío o es ilegible",
  "msg.rarUnsupported": "Los .rar no pueden extraerse en el móvil. Convierte el archivo a .zip y vuelve a intentarlo: la detección del subdirectorio raíz funcionará automáticamente.",
  "msg.filesPushed": "{done}/{total} archivo(s) subido(s) a {repo}/{branch}",
  "msg.subfolderStripped": "(Subdirectorio «{prefix}» detectado y eliminado)",
  "msg.filePushed": "Archivo subido a {repo}/{branch} (estrategia {strategy})",
  "msg.errors": "Errores",
  "msg.andOthers": "… y {n} más",
  "msg.enterDeletePath": "Introduce la ruta del directorio a eliminar",
  "msg.confirmDeleteTitle": "Confirmar eliminación",
  "msg.confirmDeleteBody": "¿Eliminar definitivamente «{path}» (y todo su contenido) de {repo}/{branch}?",
  "msg.deleteAction": "Eliminar",
  "msg.dirDeleted": "Directorio eliminado ({n} archivo(s) borrado(s)).",
  "msg.confirmClearTitle": "⚠️ Vaciar repositorio",
  "msg.confirmClearBody": "Esta acción eliminará TODOS los archivos de {repo}/{branch}. Es irreversible.\n\n¿Continuar?",
  "msg.clearAction": "Vaciar repositorio",
  "msg.repoCleared": "Repositorio vaciado — {n} archivo(s) eliminado(s).",
  "settings.title": "Ajustes",
  "settings.account": "CUENTA",
  "settings.githubProfile": "Perfil de GitHub",
  "settings.repos": "Repositorios",
  "settings.reposBadge": "repos",
  "settings.app": "APLICACIÓN",
  "settings.version": "Versión",
  "settings.language": "Idioma",
  "settings.danger": "PELIGRO",
  "settings.logout": "Cerrar sesión",
  "settings.logoutConfirmTitle": "Cerrar sesión",
  "settings.logoutConfirmBody": "Tu token se eliminará del dispositivo. ¿Continuar?",
  "settings.logoutAction": "Cerrar sesión",
};

const zh: Dict = {
  "login.tagline": "使用你的 GitHub 账号登录",
  "login.howTo": "如何登录",
  "login.step1": "点击下方的「创建令牌」",
  "login.step2": "勾选「repo」权限并生成令牌",
  "login.step3": "复制令牌并粘贴到下方输入框",
  "login.tokenLabel": "Personal Access Token",
  "login.tokenRequired": "请输入你的 GitHub 令牌",
  "login.tokenInvalid": "令牌无效。请检查权限（scope: repo）",
  "login.connect": "登录",
  "login.createToken": "创建 GitHub 令牌",
  "login.note": "你的令牌仅保存在本地，绝不会被共享。",
  "login.chooseLang": "选择语言",
  "tabs.home": "首页",
  "tabs.files": "文件",
  "tabs.profile": "我的",
  "home.add": "添加",
  "home.noCommits": "未找到任何提交...",
  "home.selectRepoHint": "选择一个仓库以查看提交记录",
  "home.currentBranch": "当前分支",
  "home.unborn": "无分支",
  "home.syncChanges": "同步更改",
  "home.synced": "提交已刷新",
  "home.remoteOrigin": "远程 · ORIGIN",
  "home.none": "无...",
  "home.clone": "克隆",
  "home.auth": "认证",
  "home.directory": "目录",
  "home.noRepoSelected": "未选择仓库...",
  "home.gitFilters": "GIT 过滤器",
  "home.gitFiltersHint": "显示当前分支的最新提交。",
  "home.appSync": "同步设置",
  "home.appSyncHint": "请在「文件」标签页配置同步偏好。",
  "home.scheduledSync": "计划同步设置",
  "home.scheduledSyncHint": "计划同步即将推出。",
  "home.chooseBranch": "切换分支",
  "home.chooseRepo": "选择仓库",
  "home.notifsOn": "通知已开启",
  "home.notifsOff": "通知已关闭",
  "home.selectRepoFirst": "请先选择一个仓库",
  "files.title": "文件",
  "files.clearSelection": "清除",
  "files.repo": "仓库",
  "files.selectRepo": "选择一个仓库...",
  "files.search": "搜索...",
  "files.noRepoFound": "未找到仓库",
  "files.branch": "分支",
  "files.targetPath": "目标路径（可选）",
  "files.targetPathPh": "例：src/components",
  "files.commitMsg": "提交信息",
  "files.commitMsgPh": "提交信息...",
  "files.file": "文件",
  "files.pickFile": "选择文件",
  "files.replaceFile": "替换文件",
  "files.zipHint": ".zip 会自动解压。检测到共同根目录（如 project-main/）时会自动去除，文件将推送到仓库根目录。不支持 .rar，请转换为 .zip。",
  "files.pushZip": "解压并推送 zip",
  "files.pushFile": "推送文件",
  "files.deleteDir": "删除目录",
  "files.deleteDirPh": "例：src/old-components",
  "files.deleteDirBtn": "删除目录",
  "files.clearRepo": "清空仓库",
  "files.clearRepoHint": "在一次提交中删除仓库的所有文件。不可撤销。",
  "files.clearRepoBtn": "清空仓库",
  "msg.error": "错误",
  "msg.success": "成功",
  "msg.cancel": "取消",
  "msg.ok": "确定",
  "msg.viewCommits": "查看提交",
  "msg.unknownError": "未知错误",
  "msg.selectRepoFirst": "请先选择一个仓库",
  "msg.noFileSelected": "未选择文件",
  "msg.enterCommitMsg": "请输入提交信息",
  "msg.pickFail": "无法选择文件",
  "msg.zipEmpty": "zip 为空或无法读取",
  "msg.rarUnsupported": "移动端无法解压 .rar。请将其转换为 .zip 后重试：根目录检测会自动生效。",
  "msg.filesPushed": "已推送 {done}/{total} 个文件到 {repo}/{branch}",
  "msg.subfolderStripped": "（检测到子目录「{prefix}」并已去除）",
  "msg.filePushed": "文件已推送到 {repo}/{branch}（策略 {strategy}）",
  "msg.errors": "错误",
  "msg.andOthers": "… 及另外 {n} 个",
  "msg.enterDeletePath": "请输入要删除的目录路径",
  "msg.confirmDeleteTitle": "确认删除",
  "msg.confirmDeleteBody": "永久删除 {repo}/{branch} 中的「{path}」（及其全部内容）？",
  "msg.deleteAction": "删除",
  "msg.dirDeleted": "目录已删除（移除了 {n} 个文件）。",
  "msg.confirmClearTitle": "⚠️ 清空仓库",
  "msg.confirmClearBody": "此操作将删除 {repo}/{branch} 的所有文件，且不可撤销。\n\n继续？",
  "msg.clearAction": "清空仓库",
  "msg.repoCleared": "仓库已清空 — 删除了 {n} 个文件。",
  "settings.title": "设置",
  "settings.account": "账户",
  "settings.githubProfile": "GitHub 个人资料",
  "settings.repos": "仓库",
  "settings.reposBadge": "仓库",
  "settings.app": "应用",
  "settings.version": "版本",
  "settings.language": "语言",
  "settings.danger": "危险操作",
  "settings.logout": "退出登录",
  "settings.logoutConfirmTitle": "退出登录",
  "settings.logoutConfirmBody": "你的令牌将从此设备移除。继续？",
  "settings.logoutAction": "退出",
};

const ru: Dict = {
  "login.tagline": "Войдите с помощью аккаунта GitHub",
  "login.howTo": "Как войти",
  "login.step1": "Нажмите «Создать токен» ниже",
  "login.step2": "Включите scope «repo» и сгенерируйте токен",
  "login.step3": "Скопируйте токен и вставьте его в поле ниже",
  "login.tokenLabel": "Personal Access Token",
  "login.tokenRequired": "Введите ваш токен GitHub",
  "login.tokenInvalid": "Неверный токен. Проверьте права (scope: repo)",
  "login.connect": "Войти",
  "login.createToken": "Создать токен GitHub",
  "login.note": "Токен хранится локально и никогда не передаётся.",
  "login.chooseLang": "Выбрать язык",
  "tabs.home": "Главная",
  "tabs.files": "Файлы",
  "tabs.profile": "Профиль",
  "home.add": "ДОБАВИТЬ",
  "home.noCommits": "КОММИТЫ НЕ НАЙДЕНЫ...",
  "home.selectRepoHint": "Выберите репозиторий, чтобы увидеть коммиты",
  "home.currentBranch": "ТЕКУЩАЯ ВЕТКА",
  "home.unborn": "НЕТ ВЕТКИ",
  "home.syncChanges": "СИНХРОНИЗИРОВАТЬ",
  "home.synced": "Коммиты обновлены",
  "home.remoteOrigin": "УДАЛЁННЫЙ · ORIGIN",
  "home.none": "Нет...",
  "home.clone": "КЛОН",
  "home.auth": "AUTH",
  "home.directory": "КАТАЛОГ",
  "home.noRepoSelected": "Репозиторий не выбран...",
  "home.gitFilters": "GIT-ФИЛЬТРЫ",
  "home.gitFiltersHint": "Показаны последние коммиты активной ветки.",
  "home.appSync": "Настройки синхронизации",
  "home.appSyncHint": "Настройте параметры во вкладке «Файлы».",
  "home.scheduledSync": "ПЛАНОВАЯ СИНХРОНИЗАЦИЯ",
  "home.scheduledSyncHint": "Плановая синхронизация скоро появится.",
  "home.chooseBranch": "Сменить ветку",
  "home.chooseRepo": "Выбрать репозиторий",
  "home.notifsOn": "Уведомления включены",
  "home.notifsOff": "Уведомления выключены",
  "home.selectRepoFirst": "Сначала выберите репозиторий",
  "files.title": "Файлы",
  "files.clearSelection": "Убрать",
  "files.repo": "РЕПОЗИТОРИЙ",
  "files.selectRepo": "Выберите репозиторий...",
  "files.search": "Поиск...",
  "files.noRepoFound": "Репозиторий не найден",
  "files.branch": "ВЕТКА",
  "files.targetPath": "ЦЕЛЕВОЙ ПУТЬ (необязательно)",
  "files.targetPathPh": "напр.: src/components",
  "files.commitMsg": "СООБЩЕНИЕ КОММИТА",
  "files.commitMsgPh": "Сообщение коммита...",
  "files.file": "ФАЙЛ",
  "files.pickFile": "Выбрать файл",
  "files.replaceFile": "Заменить файл",
  "files.zipHint": ".zip распаковывается автоматически. Общая корневая папка (напр. «project-main/») определяется и удаляется, чтобы файлы попали в корень. .rar не поддерживается: конвертируйте в .zip.",
  "files.pushZip": "Распаковать и запушить zip",
  "files.pushFile": "Запушить файл",
  "files.deleteDir": "УДАЛИТЬ КАТАЛОГ",
  "files.deleteDirPh": "напр.: src/old-components",
  "files.deleteDirBtn": "Удалить каталог",
  "files.clearRepo": "ОЧИСТИТЬ РЕПОЗИТОРИЙ",
  "files.clearRepoHint": "Удаляет ВСЕ файлы репозитория одним коммитом. Необратимо.",
  "files.clearRepoBtn": "Очистить репозиторий",
  "msg.error": "Ошибка",
  "msg.success": "Успех",
  "msg.cancel": "Отмена",
  "msg.ok": "OK",
  "msg.viewCommits": "Смотреть коммиты",
  "msg.unknownError": "Неизвестная ошибка",
  "msg.selectRepoFirst": "Сначала выберите репозиторий",
  "msg.noFileSelected": "Файл не выбран",
  "msg.enterCommitMsg": "Введите сообщение коммита",
  "msg.pickFail": "Не удалось выбрать файл",
  "msg.zipEmpty": "Zip пуст или нечитаем",
  "msg.rarUnsupported": ".rar нельзя распаковать на мобильном устройстве. Конвертируйте архив в .zip и повторите: определение корневой папки сработает автоматически.",
  "msg.filesPushed": "Запушено {done}/{total} файл(ов) в {repo}/{branch}",
  "msg.subfolderStripped": "(Папка «{prefix}» обнаружена и удалена из пути)",
  "msg.filePushed": "Файл запушен в {repo}/{branch} (стратегия {strategy})",
  "msg.errors": "Ошибки",
  "msg.andOthers": "… и ещё {n}",
  "msg.enterDeletePath": "Введите путь удаляемого каталога",
  "msg.confirmDeleteTitle": "Подтвердить удаление",
  "msg.confirmDeleteBody": "Навсегда удалить «{path}» (со всем содержимым) из {repo}/{branch}?",
  "msg.deleteAction": "Удалить",
  "msg.dirDeleted": "Каталог удалён (убрано файлов: {n}).",
  "msg.confirmClearTitle": "⚠️ Очистить репозиторий",
  "msg.confirmClearBody": "Это удалит ВСЕ файлы {repo}/{branch}. Операция необратима.\n\nПродолжить?",
  "msg.clearAction": "Очистить",
  "msg.repoCleared": "Репозиторий очищен — удалено файлов: {n}.",
  "settings.title": "Настройки",
  "settings.account": "АККАУНТ",
  "settings.githubProfile": "Профиль GitHub",
  "settings.repos": "Репозитории",
  "settings.reposBadge": "репо",
  "settings.app": "ПРИЛОЖЕНИЕ",
  "settings.version": "Версия",
  "settings.language": "Язык",
  "settings.danger": "ОПАСНАЯ ЗОНА",
  "settings.logout": "Выйти",
  "settings.logoutConfirmTitle": "Выйти",
  "settings.logoutConfirmBody": "Токен будет удалён с устройства. Продолжить?",
  "settings.logoutAction": "Выйти",
};

const DICTS: Record<LangCode, Dict> = { fr, en, es, zh, ru };

interface LanguageContextType {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>("fr");

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then((v) => {
      if (v && (["fr", "en", "es", "zh", "ru"] as string[]).includes(v)) {
        setLangState(v as LangCode);
      }
    }).catch(() => {/**/});
  }, []);

  function setLang(l: LangCode) {
    setLangState(l);
    AsyncStorage.setItem(LANG_KEY, l).catch(() => {/**/});
  }

  function t(key: string, vars?: Record<string, string | number>): string {
    let str = DICTS[lang][key] ?? DICTS.fr[key] ?? key;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        str = str.split(`{${k}}`).join(String(v));
      }
    }
    return str;
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useI18n() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useI18n must be inside LanguageProvider");
  return ctx;
}
